### ISSUE TITLE
Cannot enter value into input[text] on Safari 9 when it has the dnd-nodrag directive

### ISSUE THREAD

**Issue by jisuo** [marceljuenemann/angular-drag-and-drop-lists#150]
Using:
Safari Version 9.0 (11601.1.56)
OS X 10.11
(have not tested on other safari versions)

Example fiddle: http://jsfiddle.net/63qvw2kp/1/

**Comment by rastasheep** [comment]
Seems like click events are not propagated to input field too.

Same situation is with Firefox 41.01 on Mac.

**Comment by rastasheep** [comment]
This caused by default css styles in Safari for draggable input elements (input is draggable but it's 'stubbed' to do nothing => same effect as not draggable).

To fix this just add a css like:
```css
input[draggable="true"] {
  -webkit-user-select: text;
  -moz-user-select: text;
  -ms-user-select: text;
  user-select: text;
}
```
http://stackoverflow.com/questions/32192686/cannot-type-in-password-field-with-draggable-true-in-safari

Firefox problem is more dificult, it's a bug in Firefox:
https://bugzilla.mozilla.org/show_bug.cgi?id=800050
https://bugzilla.mozilla.org/show_bug.cgi?id=1189486
