### ISSUE TITLE
styling dndPlaceHolder class

### ISSUE THREAD

**Issue by sethiron** [marceljuenemann/angular-drag-and-drop-lists#177]
Is it possible to apply a :hover style to the dndPlaceholder class?
I would like to highlight the targeted dropzone when the user is dragging an item over top.

I have the following CSS, but it doesn't seem to be working:

```css
ul[dnd-list] li.dndPlaceholder:hover {
        border-color: #66afe9;
        outline: 0;
        -webkit-box-shadow: inset 0 1px 1px rgba(0,0,0,.075), 0 0 8px rgba(102, 175, 233, .6);
        box-shadow: inset 0 1px 1px rgba(0,0,0,.075), 0 0 8px rgba(102, 175, 233, .6);
    }
```
